# Required metadata
sonar.projectKey=sonar-demo
sonar.projectName=sonar-demo
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=http://localhost:9000

